name: Go CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.3'

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                version: v1.57.2
                args: ./...

            - name: Download dependencies
              run: go mod download

            - name: Run tests
              run: go test ./...

            - name: Build Go binary
              run: go build -o ./server main.go

            - name: Build and tag Docker image
              run: |
                docker build -t ${{ secrets.DOCKER_USERNAME}}/go-task-api:latest

            - name: Login to Docker Hub
              run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin

            - name: Push Docker image to Docker Hub
              run: docker push ${{secrets.DOCKER_USERNAME}}/go-task-api:latest
