name: Go CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23'

            - name: Install golangci-lint
              run: |
                curl -sSfl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2

            - name: Run golangci-lint
              run: $(go env GOPATH)/bin/golangci-lint run .

            - name: Download dependencies
              run: go mod download

            - name: Run tests
              run: go test ./...